name: Agentuity Deploy Action
description: "Deploy an Agentuity project"
author: "Agentuity"
branding:
  icon: 'activity'
  color: 'gray-dark'
inputs:
  project_dir:
    description: "Path to the project directory"
    required: false
    default: "."
  api_key:
    description: "Agentuity API key for authentication"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Agentuity CLI
      uses: agentuity/setup-action@main
    - name: Deploy Project
      shell: bash
      run: |
        echo "Deploying project from ${{ inputs.project_dir }}"
        cd ${{ inputs.project_dir }} && npm install && cd ..
        agentuity bundle --dir ${{ inputs.project_dir }} --deploy --api-key ${{ inputs.api_key }} --ci
