name: Agentuity Deploy Action
description: "Deploy an Agentuity project"
author: "Agentuity"
branding:
  icon: 'activity'
  color: 'gray-dark'
inputs:
  project_dir:
    description: "Path to the project directory"
    required: false
    default: "."
  api_key:
    description: "Agentuity API key for authentication"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Agentuity CLI
      uses: agentuity/setup-action@main
    - name: Get branch names.
    id: branch-names
      uses: tj-actions/branch-names@v8
    - name: Running on a pull request branch.
      if: steps.branch-names.outputs.is_default == 'false'
      run: |
        echo "Running on pr: ${{ steps.branch-names.outputs.current_branch }}"
    # Outputs: "Running on pr: feature/test"
    - name: Deploy Project
      shell: bash
      run: |
        echo "Deploying project from ${{ inputs.project_dir }}"
        agentuity bundle --dir ${{ inputs.project_dir }} --install --deploy --api-key ${{ inputs.api_key }} --ci \
          --ci-remote-url=${{ github.server_url }}/${{ github.repository }} \
          --ci-branch=${{ steps.branch-names.outputs.current_branch }} \
          --ci-commit=${{ github.sha }} \
          --ci-message="${{ github.event.head_commit.message }}" \
          --ci-git-provider=github
