name: Agentuity Deploy Action
description: "Deploy an Agentuity project"
author: "Agentuity"
branding:
  icon: 'activity'
  color: 'gray-dark'
inputs:
  project_dir:
    description: "Path to the project directory"
    required: false
    default: "."
  api_key:
    description: "Agentuity API key for authentication"
    required: true
runs:
  using: "composite"
  steps:
  - name: Setup Agentuity CLI
    uses: agentuity/setup-action@main
  - name: Set latest commit message env var
    shell: bash
    run: |
      COMMIT_MSG=$(git log -1 --pretty=format:"%s" ${{ github.event.pull_request.head.sha }} 2>/dev/null || true)
      if [ -z "$COMMIT_MSG" ]; then
        echo "::warning::Could not find commit message for ${{ github.event.pull_request.head.sha }}. Setting LATEST_COMMIT_MSG to empty string. If you need commit info, add actions/checkout@v4 with fetch-depth: 0 before this action."
      fi
      echo "LATEST_COMMIT_MSG=$COMMIT_MSG" >> $GITHUB_ENV
  - name: Deploy Project
    shell: bash
    run: |
      echo "Deploying project from ${{ inputs.project_dir }}"
      agentuity bundle --dir ${{ inputs.project_dir }} --install --deploy --api-key=${{ inputs.api_key }} --ci-remote-url=${{ github.server_url }}/${{ github.repository }} --ci-branch=${{ github.head_ref }} --ci-commit=${{ github.event.pull_request.head.sha }} --ci-git-provider=github --ci-message=${{ env.LATEST_COMMIT_MSG }} --ci 